// DatabaseObject properties
export const DataKeys = {
  OVERVIEW: 'overview',
  LITERATURE_REFERENCE: 'literatureReference',
  REFERENCE_ENTITY: 'referenceEntity',
  CROSS_REFERENCES: 'crossReferences',
  AUTHORED: 'authored',
  REVIEWED: 'reviewed',
  EDITED: 'edited',
  REVISED: 'revised',
  INPUT: 'inputs',
  OUTPUT: 'outputs',
  CATALYST_ACTIVITY: 'catalystActivity',
  CATALYST_ACTIVITY_REFERENCE: 'catalystActivityReference',
  OTHER_FORMS: 'otherForms',
  INFERRED_TO: 'inferredTo',
  SUMMATION: 'summation',
  CATEGORY: 'category',
  CLASS_NAME: 'className',
  SPECIES_NAME: 'speciesName',
  COMPARTMENT: 'hasCompartment',
  NAME: 'name',
  TISSUE: 'tissue',
  REVIEW_STATUS: 'reviewStatus',
  PUBLICATION: 'publication',
  INTERACTORS: 'interactors',
  AUTHORSHIP: 'authorship',
  INFERRED_FROM: 'inferredFrom',
  PRECEDING_EVENT: 'precedingEvent',
  FOLLOWING_EVENT: 'followingEvent',
  COMPONENTS: 'components',
  INPUT_FOR: 'inputFor',
  OUTPUT_FOR: 'outputFor',


} as const;


// Labels
export const Labels = {
  OVERVIEW: 'Overview',
  AUTHOR: 'Author',
  REVIEWER: 'Reviewer',
  EDITOR: 'Editor',
  REVISER: 'Reviser',
  CROSS_REFERENCES: 'Cross References',
  REFERENCE: 'References',
  EXTERNAL_REFERENCE: 'External Reference',
  AUTHORSHIP: 'Authorship',
  INPUTS: 'Inputs',
  OUTPUTS: 'Outputs',
  CATALYST_ACTIVITY: 'Catalyst Activity',
  OTHER_FORMS: 'Other forms',
  INFERENCES: 'Inferences',
  INTERACTORS: 'Interactors',
  INFERRED_FROM: 'Inferred From',
  PRECEDING_EVENT: 'Preceding Event',
  FOLLOWING_EVENT: 'Following Events',
  COMPONENTS: 'Components',
  INPUT_FOR: 'Consumed by',
  OUTPUT_FOR: 'Produced by',
} as const;

export const SchemaClasses = {
  EWAS: 'EntityWithAccessionedSequence',
  PE: 'PhysicalEntity',
  COMPLEX: 'Complex',
  DRUG: 'Drug',
  CHEMICAL_DRUG: 'ChemicalDrug',
  PROTEIN_DRUG: 'ProteinDrug',
  RNA_DRUG: 'RNADrug',
  ENTITY_SET: 'EntitySet',
  CANDIDATE_SET: 'CandidateSet',
  GENOME_ENCODED_ENTITY: 'GenomeEncodedEntity',
  OTHER_ENTITY: 'OtherEntity',
  POLYMER: 'Polymer',
  SIMPLE_ENTITY: 'SimpleEntity',


  PATHWAY: 'Pathway',
  TLP: 'TopLevelPathway',
  CELL_LINEAGE_PATH: 'CellLineagePath',
  REACTION: 'Reaction',
  BLACK_BOX_EVENT: 'BlackBoxEvent',
  POLYMERISATION: 'Polymerisation',
  DEPOLYMERISATION: 'Depolymerisation',
  FAILED_REACTION: 'FailedReaction',
  CELL_DEVELOPMENT_STEP: 'CellDevelopmentStep',
  CATALYST_ACTIVITY: 'CatalystActivity'

} as const
